version: "3.7"
services:
  ion_dev:
    build:
      context: ./ionic
    container_name: ion_dev
    volumes:
      - ./:/app
    ports: 
      - 8100:8100
      - 35729:35729
      - 53703:53703
    environment: 
      - APP_NAME=ionapp
      - APP_TYPE=vue # angular, react, vue